#!/bin/bash
sudo yum -y install httpd mod_ssl                     # this installs apache with encryption
sudo systemctl enable httpd                           # this enables the apache service
sudo systemctl start httpd                            # this starts the apache server



sudo sed -i 's/^/#/g' /etc/httpd/conf.d/welcome.conf                      # commenting out welcome.conf
                                                             
sudo echo -e "<html> \n<h1> welcome, NTI -300 </h1> \n</html>" > /var/www/html/index.html          #reating our index.html
